# 使用的语言文件名 语言文件需要被储存在 LandsQQBot/lang/ 目录下
lang: zh-CN.yml

# 机器人相关的配置
bot:
  # 机器人使用的 QQ 账号
  account: 2277179500

# QQ 相关的配置
qq:
  # 机器人在哪些群工作
  # 若使用 * 作为参数，则意味着该机器人账户所在的所有群聊中的消息
  # 都会触发本插件的效果
  # 如果你的机器人使用的账号不止用于一个服务器，那么你可以仅对
  # 安装了 Lands 插件的服务器的交流群开放本插件
  groups:
    - "*"

  # 用于对特定的 QQ 群聊户禁用本插件的功能
  # 可以用于拉黑恶意滥用插件功能的群
  groups-blacklist:
    - 12345

  # 机器人对哪些人的消息做出反应
  # 若使用 * 作为参数，则意味着这个机器人账户的所有好友的消息
  # 都会触发本插件的效果
  # 可以用于对管理开放私人查询的功能
  friends:
    - "*"

  # 用于对特定的 QQ 账户禁用本插件的功能
  # 可以用于拉黑恶意滥用插件功能的玩家
  friends-blacklist:
    - 12345

lands:
